name: Deploy via SSH to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Copy .env to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".env"
          target: "/home/ec2-user/app/.env"        # onde vai ficar o .env

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.SSH_HOSTNAME }} >> ~/.ssh/known_hosts

      - name: Remote deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1) Criar a pasta e entrar nela
            mkdir -p /home/ec2-user/app
            cd /home/ec2-user/app

            # 2) Se ainda não tiver .git, clona; senão, dá pull
            if [ ! -d .git ]; then
              git clone https://github.com/rsaPeres/zero-double-blind-core.git . 
            else
              git pull origin main
            fi

            # 3) Parar e subir containers
            if command -v docker-compose; then
              docker-compose down
              docker-compose up -d --build
            else
              docker compose down
              docker compose up -d --build
            fi
