name: Deploy via SSH to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy .env to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".env"
          target: "/home/.env"


      - name: Setup SSH key
        run: |
          # 1) Cria o diretório .ssh
          mkdir -p ~/.ssh

          # 2) Grava a chave privada (vinda do secret SSH_PRIVATE_KEY)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

          # 3) Restringe permissão da chave (apenas dono pode ler)
          chmod 600 ~/.ssh/id_rsa

          # 4) Adiciona hosts confiáveis para evitar prompt interativo
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.SSH_HOSTNAME }} >> ~/.ssh/known_hosts

      - name: Remote deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}       # ex: 3.142.96.23
          username: ec2-user                  # ou 'ubuntu', conforme AMI
          key: ${{ secrets.SSH_PRIVATE_KEY }} # mesma chave em id_rsa
          script: |
            cd /home
            git pull origin main
            docker-compose down
            docker-compose up -d --build
