pub mod user_entity;
pub mod patient_entity;
pub mod interview_entity;
pub mod interview_status_entity;
mod answer_entity;
mod auditable_entity;
mod clinical_trial_status_entity;
mod clinical_trail_entity;
mod form_entity;
mod group_assignment_entity;
mod interview_stage_entity;
mod participant_data_entity;
mod participant_profile_entity;
mod question_entity;
mod researcher_entity;