name: Deploy zero-double-blind-core to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Copy .env to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".env"
          target: "/home/ec2-user/zero-double-blind-core/.env"

      - name: Setup SSH key no runner
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # coleta a fingerprint do GitHub
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # coleta a fingerprint da sua EC2 (SSH_HOST armazena só o IP ou hostname)
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Remote deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            APP_DIR=/home/ec2-user/zero-double-blind-core

            # 1) Cria pasta do app (se ainda não existir) e entra nela
            mkdir -p $APP_DIR
            cd $APP_DIR

            # 2) Clona na primeira vez ou puxa updates depois
            
            if [ ! -d .git ]; then
              git init
              git remote add origin https://github.com/${{ github.repository }}.git
              git fetch origin main
              git checkout -b main origin/main
            else
              # Atualiza tudo pra última versão limpa da main
              git fetch origin main
              git reset --hard origin/main
            fi

            # 3) Sobe containers com Docker Compose v2
            docker compose down
            docker compose up -d --build